### ISSUE TITLE
How to make Mac Mini use this network card driver?

### ISSUE THREAD

**Issue by zs2766** [Mieze/IntelLucy#6]
I have a Mac mini that is connected to an Intel X520 network card through the Thunderbolt 4 interface, but cannot enable jumbo frames. I need to use this driver, but I don't know how to use it on the Mac mini. I see that other drivers are installed. Can you help me? thank you!

**Comment by zs2766** [comment]
Can the kext file be encapsulated as a pkg file for installation?

**Comment by Mieze** [comment]
Thunderbolt support isn't implemented in IntelLucy at the moment because there are two things missing:

1. Add a property to the driver's Info.plist file to indicate thunderbolt support. That can be done within a minute.
2. Properly handle device removal, which is the most difficult and laborious part.

Besides that, what kind of Mac mini are you using? In case it's an Intel based machine, SIP has to be enabled and the driver must be installed in /Library/Extensions because it's not code signed and I don't have the entitlement to code sign kexts. Machines with Apple Silicon are unsupported because they require a slightly different driver design.

**Comment by zs2766** [comment]
> Thunderbolt support isn't implemented in IntelLucy at the moment because there are two things missing:
> 
> 1. Add a property to the driver's Info.plist file to indicate thunderbolt support. That can be done within a minute.
> 2. Properly handle device removal, which is the most difficult and laborious part.
> 
> Besides that, what kind of Mac mini are you using? In case it's an Intel based machine, SIP has to be disabled and the driver must be installed in /Library/Extensions because it's not code signed and I don't have the entitlement to code sign kexts. Machines with Apple Silicon are unsupported because they require a slightly different driver design.
> 
> EDIT: Clarified that SIP must be disabled!

Sorry, I may not have explained it clearly to you. I am using Apple's latest Mac mini M4, which has not yet arrived in my hands. I plan to use the Thunderbolt 4 interface to transfer to the NVMe interface, and then use the NVMe interface to transfer to the PCIe interface and plug it into the X52 Gigabit network card for use. If SIP must be disabled, I can accept it. I don't know how to use your driver on Mac mini. Can you package the pkg file format so that it can be directly installed on Mac for use? Thank you

**Comment by Mieze** [comment]
Sorry, but IntelLucy is not designed to run on Apple Silicon based Macs. What you are planning is not possible. You should get a Mac mini with an integrated 10GBase-T interface.

**Comment by smitty078** [comment]
@Mieze I found this issue while investigating Thunderbolt support for this driver for use with an Intel Mac mini. If I don't care about device removal, would this theoretically work by adding the appropriate plist key? Understanding that it would not be handled properly (as Apple would want), would anything bad happen (for example a kernel panic) with host shutdown or accidental device removal?

**Comment by Mieze** [comment]
If you are willing to test, I'm going to implement the missing code during the next days? Please write directly to laura-mueller@uni-duesseldorf.de and I'll send you the test versions ASAP.

**Comment by photovirus** [comment]
> Sorry, but IntelLucy is not designed to run on Apple Silicon based Macs. What you are planning is not possible. You should get a Mac mini with an integrated 10GBase-T interface.

Has anything changed on this front? I've seen that Thunderbolt support is already in there. 

I've got an Arm-based Mac, and I'd like to use this driver because stock Apple driver lacks jumbo frames support for some reason. Is it unreasonable effort to attempt to modify the driver into an Arm-compatible dext package?
